### ISSUE TITLE
Roadmap to 11.3

### ISSUE THREAD

**Issue by wirew0rm** [fair-acc/chart-fx#527]
This is the roadmap issue collecting issues potentially breaking API, which should be addressed for the 11.3 release.

This announcement is here to track progress, but also to collect feedback from the community and to catch potential problems for consumers of the library early on.

- [x] move main branch: `master` -> `main` to unify with our other repositories
- [x] change package names: `de.gsi` -> `io.fair_acc.chartfx` (change new github coordinate, pom-xml etc.)
- [x] versioning: officially deprecate/freeze jdk8 release?
- [ ] porting of ThreadPooling helper class (i.e. add optional Executor interface)? thread affinity, add api for specifying pool to use
- [x] refactor layouting code to reduce hierarchy depth and increase flexibility (e.g. 3D plots) #529
- [x] #530
- [x] <strike>open question/idea: using https://github.com/ReactiveX/RxJava ?? `Flowable<DataSet> (primarily DataSetMath)</strike>
- [ ] improve the CI/CD workflow and minimise flakes
- [ ] act on outstanding GitHub issues:
   - patch available
   - [x] #523
   - [x] #490 (fix for windows, ensure compatibility with linux)
   - [x] #484
   -  needs investigation
   - [x] #517
   - [x] #508
   - [x] #491
   - [ ] #489
   - [ ] #524
   - should be handled together with layouting/event system
   - [ ] #474
   - [x] #410
   - others
   - [ ] #204
   - [ ] #163
   - [ ] #47
- [x] remove microservice module after verifying that everything in it is provided by [opencmw-java](https://github.com/fair-acc/opencmw-java)
- [x] report plugin dependency issue to jetbrains: [jetbrains-issue](https://youtrack.jetbrains.com/issue/IDEA-296729/Maven-plugins-are-not-resolved-from-the-parent-in-modularized)
- [x] openjfx: 13 -> 20, this is done at the end to ensure compatibility with older javafx versions
- [x] JDK: 11 -> 17 + 20 on main, introduce jdk11 compatibility branch? (nb openjfx 20 requires jdk >=17)
- [x] chart-fx logo #528

**Comment by brainbytes42** [comment]
The library sounds promising - getting it was a little confusing at first. The readme has already the new maven-target ('io.fair-acc:chartfx:11.3.0'), which isn't released yet. The currently released version ('de.gsi:chartfx:11.2.7') would be more helpful there... ;-)

**Comment by crowlogic** [comment]
Exception in Application start method
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:464)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1081)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NoSuchMethodError: 'void javafx.scene.canvas.GraphicsContext.setImageSmoothing(boolean)'
	at de.gsi.chartfx.chart@11.2.7/de.gsi.chart.renderer.spi.ContourDataSetRenderer.drawHeatMap(ContourDataSetRenderer.java:200)
	at de.gsi.chartfx.chart@11.2.7/de.gsi.chart.renderer.spi.ContourDataSetRenderer.paintCanvas(ContourDataSetRenderer.java:383)
	at de.gsi.chartfx.chart@11.2.7/de.gsi.chart.renderer.spi.ContourDataSetRenderer.render(ContourDataSetRenderer.java:433)
	at de.gsi.chartfx.chart@11.2.7/de.gsi.chart.XYChart.redrawCanvas(XYChart.java:433)
	at de.gsi.chartfx.chart@11.2.7/de.gsi.chart.Chart.layoutChildren(Chart.java:756)

**Comment by crowlogic** [comment]
> The library sounds promising - getting it was a little confusing at first. The readme has already the new maven-target ('io.fair-acc:chartfx:11.3.0'), which isn't released yet. The currently released version (~'de.gsi:chartfx:11.2.7'~ 'de.gsi.chart:chartfx-chart:11.2.7') would be more helpful there... ;-)

You are right of course but apparently the maintainers of this project are doing other things or got stampeded by a herd of buffalo or something

**Comment by wirew0rm** [comment]
Since the major points on the 11.3 milestone have now been addressed, the current state of the main branch will become the 11.3 release in the next days.
It brings lots of (mostly internal) reworking that massively improves performance, reliability and maintainability, lot of the hard work there was done by [ennerf (Florian Enner)](https://matrix.to/#/@ennerf-5599fbc715522ed4b3e37064:gitter.im)
. You can take a look at his PRs which include measurements and before/after comparisons. These improvements also come with very little changes to existing user code.
The biggest user facing change is the move from the de.gsi.chart* package name to io.fair_acc.chart-fx.*. While it is a bit annoying it should be mostly mechanical renames.
You can already test the main branch with the snapshot release as described in the [README.md](http://readme.md/) or wait for the imminent release. Let us know if you encounter any problems.

**Comment by protogenes** [comment]
Please make it possible to adjust line join and line cap for renderers and/or change the default values.
When rendering data as a polyline with very acute angles the joins are drawn with very large miters (easily above 30px) and that really distorts the chart.

**Comment by ennerf** [comment]
@protogenes Can you provide an example and screenshot that show the problem with the default settings?

The default renderers don't set those values, so as an initial workaround you should be able to globally modify the defaults, e.g.,

```Java
var chart = new XYChart(xAxis, yAxis);
var gc= chart.getCanvas().getGraphicsContext2D();
gc.setLineCap(StrokeLineCap.ROUND);
gc.setMiterLimit(1);
```

If you need something more localized you could extend the renderer

```Java
var renderer = new ErrorDataSetRenderer() {
    @Override
    protected void render(final GraphicsContext gc, final DataSet dataSet, final DataSetNode style) {
        gc.save();
        gc.setLineCap(StrokeLineCap.ROUND);
        gc.setMiterLimit(1);
        super.render(gc, dataSet, style);
        gc.restore();
    }
};
```

**Comment by protogenes** [comment]
@ennerf thanks, I also used a custom renderer.

```java
public class Demo extends Application {
	@Override
	public void start(Stage primaryStage) throws Exception {
		XYChart chart = new XYChart();
		DefaultDataSet dataSet = new DefaultDataSet("miter demo",
				new double[]{1, 2, 3},
				new double[]{1, 2, 1},
				3,
				false);
		dataSet.setStyle("-fx-line-width: 6"); // make it more obvious

		BasicDataSetRenderer renderer = new BasicDataSetRenderer(dataSet);
		chart.getRenderers().setAll(renderer);

		chart.getXAxis().setAutoRanging(false);
		chart.getXAxis().setMin(0);
		chart.getXAxis().setMax(100);

		chart.getYAxis().setAutoRanging(false);
		chart.getYAxis().setMin(0);
		chart.getYAxis().setMax(10);

		primaryStage.setScene(new Scene(chart));
		primaryStage.show();
	}
}
```
Produces the following render that makes it hard to read the maximum value.
Depending on the overall appearance of the data it can give the wrong impression.
For reference: the default miter limit is 10 which means the line can extend ten times the line width above the value.
![grafik](https://github.com/fair-acc/chart-fx/assets/2518035/4f120225-7268-4361-9005-87ba6971a6ed)

Another issue I encountered: StyleBuilder uses `0x%02x%02x%02x%02x` as a color format, but Java-FX and CSS use a `#` prefix.

**Comment by ennerf** [comment]
Thanks, the hex string was an oversight.

What would you want the default values to be?

**Comment by wirew0rm** [comment]
Thanks for bringing this up @protogenes (would even have warranted a dedicated issue i guess.)

From first impulse, a value of 1 seems to be reasonable,  since that would from my understanding mean that the value would never exceed the linewidth, which would be what i would expect.
Line Join is a bit more difficult, round seeems plausible but might be a bit more expensive? we usually don't have line widths where that would make a real difference.

Imo it would be sufficient to change it to a reasonable value if not someone else thinks of a usecase where it would have to be user modified. If you would prepare a PR to change it in the renderer and add some before after screenshots i would gladly merge that.

**Comment by protogenes** [comment]
I'm going with
```java
gc.setLineJoin(StrokeLineJoin.BEVEL);
gc.setLineCap(StrokeLineCap.BUTT);
```
because when exceeding the miter limit the join will fall back to a bevel anyways and these differences/changes in representation might be irritating for our time series.

**Comment by yezhengli-Mr9** [comment]
> * [x]  change package names: `de.gsi` -> `io.fair_acc.chartfx` (change new github coordinate, pom-xml etc.)

Any way to check earlier version of `de.gsi` for non-internal developer like me? To fix issues like #639.
Not for sure following works
```java
git clone -b 11.2.0 git@github.com:fair-acc/chart-fx.git
git swich -c 11.2.0
```
